# Generated by Django 2.1.1 on 2018-09-20 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0002_auto_20180920_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='tank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tank_doc1', to='tanks.Tank'),
        ),
    ]
