# Generated by Django 2.0.8 on 2018-09-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0003_auto_20180920_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='doc_rev_1',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='general',
            name='doc_rev_2',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='general',
            name='doc_rev_3',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='general',
            name='doc_rev_4',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='general',
            name='doc_rev_5',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='generalpart',
            name='doc_rev_1',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='generalpart',
            name='doc_rev_2',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='generalpart',
            name='doc_rev_3',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='generalpart',
            name='doc_rev_4',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='generalpart',
            name='doc_rev_5',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='generalwelding',
            name='doc_rev_1',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='generalwelding',
            name='doc_rev_2',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='generalwelding',
            name='doc_rev_3',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='generalwelding',
            name='doc_rev_4',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='generalwelding',
            name='doc_rev_5',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='rt',
            name='doc_rev_1',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='rt',
            name='doc_rev_2',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='rt',
            name='doc_rev_3',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='rt',
            name='doc_rev_4',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='rt',
            name='doc_rev_5',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='tank',
            name='doc_rev_1',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='tank',
            name='doc_rev_2',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='tank',
            name='doc_rev_3',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='tank',
            name='doc_rev_4',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='tank',
            name='doc_rev_5',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='ut',
            name='doc_rev_1',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='ut',
            name='doc_rev_2',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='ut',
            name='doc_rev_3',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='ut',
            name='doc_rev_4',
            field=models.FileField(null=True, upload_to='doct'),
        ),
        migrations.AddField(
            model_name='ut',
            name='doc_rev_5',
            field=models.FileField(null=True, upload_to='doct'),
        ),
    ]
