# Generated by Django 2.0.8 on 2018-09-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0004_auto_20180928_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='doc_rev_1',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='doc_rev_2',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='doc_rev_3',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='doc_rev_4',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='doc_rev_5',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
    ]
