# Generated by Django 2.0.8 on 2018-09-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0005_auto_20180928_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='doc_rev_1',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='general',
            name='doc_rev_2',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='general',
            name='doc_rev_3',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='general',
            name='doc_rev_4',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='general',
            name='doc_rev_5',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='generalpart',
            name='doc_rev_1',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='generalpart',
            name='doc_rev_2',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='generalpart',
            name='doc_rev_3',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='generalpart',
            name='doc_rev_4',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='generalpart',
            name='doc_rev_5',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='generalwelding',
            name='doc_rev_1',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='generalwelding',
            name='doc_rev_2',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='generalwelding',
            name='doc_rev_3',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='generalwelding',
            name='doc_rev_4',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='generalwelding',
            name='doc_rev_5',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='rt',
            name='doc_rev_1',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='rt',
            name='doc_rev_2',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='rt',
            name='doc_rev_3',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='rt',
            name='doc_rev_4',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='rt',
            name='doc_rev_5',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='ut',
            name='doc_rev_1',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='ut',
            name='doc_rev_2',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='ut',
            name='doc_rev_3',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='ut',
            name='doc_rev_4',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
        migrations.AlterField(
            model_name='ut',
            name='doc_rev_5',
            field=models.FileField(blank=True, null=True, upload_to='doct'),
        ),
    ]
