# Generated by Django 2.0.8 on 2018-09-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0006_auto_20180928_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='tank',
        ),
        migrations.DeleteModel(
            name='DocumentFile',
        ),
    ]
