# Generated by Django 2.0.8 on 2018-10-30 06:24

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0007_auto_20180928_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalwelding',
            name='PT_Result',
        ),
        migrations.AddField(
            model_name='generalwelding',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalwelding',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 6, 24, 53, 932526, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
