# Generated by Django 2.0.8 on 2018-10-30 06:27

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0008_auto_20181030_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 6, 27, 50, 864113, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalpart',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
