# Generated by Django 2.0.8 on 2018-10-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0009_auto_20181030_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='Point_Course',
            new_name='Joint_Course',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='Point_Degree',
            new_name='Joint_Degree',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='Point_No',
            new_name='Joint_No',
        ),
    ]
