# Generated by Django 2.1 on 2018-09-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180826_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subContractor', models.CharField(max_length=255)),
                ('contractor', models.CharField(max_length=255, unique=True)),
                ('consultant', models.TextField(blank=True, null=True)),
                ('tpa', models.TextField(blank=True, null=True)),
                ('mc', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(max_length=255)),
                ('subproject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project', to='projects.Project')),
            ],
        ),
    ]
