# Generated by Django 2.1 on 2018-09-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180902_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproject',
            old_name='subproject',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='subproject',
            old_name='subContractor',
            new_name='subcontractor',
        ),
    ]
