# Generated by Django 2.1 on 2018-09-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
    ]
