# Generated by Django 2.0.8 on 2018-09-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180908_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('revision', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='doct')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tank_project', to='projects.Project')),
            ],
        ),
    ]
